title: "zk"
permalink: /:title
defaults:
  - scope:
      path: "README.md"
    values:
      title: "zk"
  - scope:
      path: "" # all
    values:
      render_with_liquid: false
exclude:
  - ".github/"
  - ".gitignore"
  - "CHANGELOG.md"
  - "CONTRIBUTING.md"
  - "LICENSE"
  - "Makefile"
  - "go.mod"
  - "go.sum"
  - "internal/"
  - "main.go"
  - "tests/"

