name: Enhancement
description: Something that exists, but can be improved.
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
        Describe the enhancement. What is currently not working so well? And how
        can it be improved?
  - type: checkboxes
    id: ownership
    attributes:
      label: "Do I plan to submit a PR for this?"
      options:
        - label: "No"
        - label: "Yes"
