name: Feature Request
description: Suggest a new feature or enhancement for this project.
title: "<do not include bug:, feat:, etc>"
labels:
  - feature request
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
        Describe the feature. Why should it be implemented? What problem does it
        solve? What value does it bring? How would it help users?
  - type: checkboxes
    id: ownership
    attributes:
      label: Ownership
      description: "Do I plan to submit a PR for this feature?"
      options:
        - label: "No"
        - label: "Yes"
