name: Deploy Sphinx documentation

# NOTE: workflow uses this repo: https://github.com/sphinx-notes/pages

on:
  push:
    branches: [feat-sphinx-docs] # branch to trigger deployment


jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3

